workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      java: 21
      node: 22

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Expo prebuild (generate native Android project)
        script: npx expo prebuild --platform android --clean

      - name: Build Android APK (Debug)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
